### ISSUE TITLE
How to insert an own initial simplex matrix into the nelder mead algorithm

### ISSUE THREAD

**Issue by jxsl13** [DeveloperPaul123/Optimum#5]
As I'm not knowledgeable how the actual nelder mead works(at least the theoretical part), but still need to use it , I would like to ask how to insert an own initial simplex matrix of the dimensions (dim+1)x(dim) into this algorithm.
Thanks for your time.

**Comment by ptsouchlos** [comment]
@jxsl13 Currently matrices of arbitrary dimensions are not possible. The nelder mead implementation only supports n x 1 vector inputs.

**Comment by jxsl13** [comment]
What would happen if I added the rows of the matrix as initial guess inputs :?

**Comment by ptsouchlos** [comment]
> What would happen if I added the rows of the matrix as initial guess inputs :?

Do you mean treat each row of the matrix as its own vector?

**Comment by jxsl13** [comment]
yes.

**Comment by ptsouchlos** [comment]
@jxsl13 If the rows of each matrix are in fact independent then you can do this and it will work fine (I think).

**Comment by jxsl13** [comment]
I mean to initially add all rows and then run the algorithm. Or did you mean to add each row as an own initial vector and then run the algorithm?
Thanks btw.

**Comment by ptsouchlos** [comment]
The nelder mead algorithm can only work on 1 vector at a time currently. So there's no way to "add all rows" and then run the algorithm. 

The flow would be add row -> process -> get result. Add row -> process -> get result ...and so on.
